export const products = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    name: "QHM AquaShield Waterproof Coating 4kg",
    category: "waterproofing",
    brand: "QHM",
    description: "Pelapis anti bocor berbahan akrilik untuk dak beton, talang, dan area rembes ringan.",
    use_cases: ["atap bocor", "dak beton", "waterproofing", "talang rembes"],
    unit: "pail 4 kg",
    price: 235000,
    stock_status: "in_stock",
    coverage_note: "Sekitar 4 m2 per pail per coat, tergantung permukaan.",
    metadata: { pack_size_kg: 4, coverage_kg_per_m2_per_coat: 1 }
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    name: "QHM RoofSeal Waterproof Coating 20kg",
    category: "waterproofing",
    brand: "QHM",
    description: "Waterproofing elastomeric ukuran proyek untuk atap, dak, dan balkon.",
    use_cases: ["atap bocor", "dak beton", "balkon", "waterproofing area luas"],
    unit: "pail 20 kg",
    price: 890000,
    stock_status: "in_stock",
    coverage_note: "Sekitar 20 m2 per pail per coat, rekomendasi 2 coat.",
    metadata: { pack_size_kg: 20, coverage_kg_per_m2_per_coat: 1 }
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    name: "QHM Fiber Mesh Waterproofing 1m x 10m",
    category: "waterproofing",
    brand: "QHM",
    description: "Serat penguat untuk sudut, retak rambut, sambungan dak, dan area rawan bocor.",
    use_cases: ["retak dak", "sambungan atap", "waterproofing membrane", "atap bocor"],
    unit: "roll",
    price: 145000,
    stock_status: "in_stock",
    coverage_note: "Roll 10 m2 untuk penguatan lokal atau seluruh bidang.",
    metadata: { roll_area_m2: 10 }
  },
  {
    id: "10000000-0000-4000-8000-000000000004",
    name: "QHM PU Sealant 300ml",
    category: "waterproofing",
    brand: "QHM",
    description: "Sealant polyurethane untuk celah, sambungan talang, flashing, dan retak aktif.",
    use_cases: ["celah bocor", "talang", "flashing", "retak sambungan"],
    unit: "cartridge 300 ml",
    price: 78000,
    stock_status: "in_stock",
    coverage_note: "Kebutuhan tergantung lebar dan kedalaman celah.",
    metadata: { volume_ml: 300 }
  },
  {
    id: "10000000-0000-4000-8000-000000000005",
    name: "Nippon Vinilex Interior Paint 2.5L",
    category: "paint",
    brand: "Nippon Paint",
    description: "Cat tembok interior untuk kamar, ruang keluarga, dan plafon.",
    use_cases: ["cat dinding interior", "repaint kamar", "plafon"],
    unit: "pail 2.5 L",
    price: 185000,
    stock_status: "in_stock",
    coverage_note: "Sekitar 25 m2 per pail per coat.",
    metadata: { pack_size_l: 2.5, coverage_m2_per_pack_per_coat: 25 }
  },
  {
    id: "10000000-0000-4000-8000-000000000006",
    name: "Jotun Jotashield Exterior Paint 2.5L",
    category: "paint",
    brand: "Jotun",
    description: "Cat eksterior tahan cuaca untuk fasad, pagar tembok, dan area luar.",
    use_cases: ["cat eksterior", "dinding luar", "fasad", "repaint luar rumah"],
    unit: "pail 2.5 L",
    price: 265000,
    stock_status: "in_stock",
    coverage_note: "Sekitar 22 m2 per pail per coat.",
    metadata: { pack_size_l: 2.5, coverage_m2_per_pack_per_coat: 22 }
  },
  {
    id: "10000000-0000-4000-8000-000000000007",
    name: "QHM Alkali Sealer Primer 2.5L",
    category: "paint",
    brand: "QHM",
    description: "Primer alkali untuk tembok baru atau tembok lembap sebelum pengecatan.",
    use_cases: ["primer cat", "tembok baru", "tembok lembap", "cat mengelupas"],
    unit: "pail 2.5 L",
    price: 155000,
    stock_status: "in_stock",
    coverage_note: "Sekitar 25 m2 per pail per coat.",
    metadata: { pack_size_l: 2.5, coverage_m2_per_pack_per_coat: 25 }
  },
  {
    id: "10000000-0000-4000-8000-000000000008",
    name: "QHM Paint Roller Set 9 inch",
    category: "paint",
    brand: "QHM",
    description: "Set roller cat dengan tray untuk dinding interior dan eksterior.",
    use_cases: ["alat cat", "roller dinding", "repaint kamar"],
    unit: "set",
    price: 69000,
    stock_status: "in_stock",
    coverage_note: "Cocok untuk cat tembok dan waterproofing cair.",
    metadata: { roller_width_inch: 9 }
  },
  {
    id: "10000000-0000-4000-8000-000000000009",
    name: "PVC Pipe AW 1/2 inch 4m",
    category: "plumbing",
    brand: "QHM",
    description: "Pipa PVC tekanan untuk suplai air bersih rumah tangga.",
    use_cases: ["pipa air", "saluran air bersih", "plumbing"],
    unit: "batang 4 m",
    price: 42000,
    stock_status: "in_stock",
    coverage_note: "Panjang 4 meter per batang.",
    metadata: { length_m: 4, diameter_inch: 0.5, class: "AW" }
  },
  {
    id: "10000000-0000-4000-8000-000000000010",
    name: "PVC Pipe D 3/4 inch 4m",
    category: "plumbing",
    brand: "QHM",
    description: "Pipa PVC untuk buangan ringan dan saluran air non-tekanan.",
    use_cases: ["pipa buangan", "saluran air", "plumbing"],
    unit: "batang 4 m",
    price: 39000,
    stock_status: "in_stock",
    coverage_note: "Panjang 4 meter per batang.",
    metadata: { length_m: 4, diameter_inch: 0.75, class: "D" }
  },
  {
    id: "10000000-0000-4000-8000-000000000011",
    name: "PVC Elbow 90 AW 1/2 inch",
    category: "plumbing",
    brand: "QHM",
    description: "Sambungan siku 90 derajat untuk instalasi pipa PVC 1/2 inch.",
    use_cases: ["sambungan pipa", "belokan pipa", "plumbing"],
    unit: "pcs",
    price: 6500,
    stock_status: "in_stock",
    coverage_note: "Gunakan sesuai jumlah titik belokan.",
    metadata: { diameter_inch: 0.5, angle_degree: 90 }
  },
  {
    id: "10000000-0000-4000-8000-000000000012",
    name: "QHM PVC Glue 100g",
    category: "plumbing",
    brand: "QHM",
    description: "Lem pipa PVC untuk sambungan pipa air dan fitting.",
    use_cases: ["lem pipa", "sambungan pvc", "plumbing"],
    unit: "kaleng 100 g",
    price: 28000,
    stock_status: "in_stock",
    coverage_note: "Cukup untuk beberapa sambungan kecil.",
    metadata: { pack_size_g: 100 }
  },
  {
    id: "10000000-0000-4000-8000-000000000013",
    name: "QHM PTFE Seal Tape",
    category: "plumbing",
    brand: "QHM",
    description: "Seal tape untuk drat keran, shower, valve, dan sambungan berulir.",
    use_cases: ["drat bocor", "keran bocor", "seal tape", "plumbing"],
    unit: "roll",
    price: 9000,
    stock_status: "in_stock",
    coverage_note: "Satu roll untuk banyak sambungan drat kecil.",
    metadata: { tape_type: "ptfe" }
  },
  {
    id: "10000000-0000-4000-8000-000000000014",
    name: "QHM Ceramic Floor Tile 40x40 White",
    category: "tiles",
    brand: "QHM",
    description: "Keramik lantai putih ukuran 40x40 cm untuk area dalam rumah.",
    use_cases: ["keramik lantai", "renovasi lantai", "ubin"],
    unit: "box",
    price: 118000,
    stock_status: "in_stock",
    coverage_note: "Satu box sekitar 1.44 m2.",
    metadata: { tile_size_cm: "40x40", box_area_m2: 1.44 }
  },
  {
    id: "10000000-0000-4000-8000-000000000015",
    name: "QHM Tile Adhesive 25kg",
    category: "tiles",
    brand: "QHM",
    description: "Perekat keramik berbasis semen untuk lantai dan dinding.",
    use_cases: ["perekat keramik", "pasang ubin", "renovasi lantai"],
    unit: "bag 25 kg",
    price: 96000,
    stock_status: "in_stock",
    coverage_note: "Sekitar 5 m2 per bag, tergantung trowel dan permukaan.",
    metadata: { pack_size_kg: 25, coverage_m2_per_pack: 5 }
  },
  {
    id: "10000000-0000-4000-8000-000000000016",
    name: "QHM Tile Grout 1kg Grey",
    category: "tiles",
    brand: "QHM",
    description: "Nat keramik warna abu-abu untuk celah lantai dan dinding.",
    use_cases: ["nat keramik", "grout", "celah ubin"],
    unit: "bag 1 kg",
    price: 24000,
    stock_status: "in_stock",
    coverage_note: "Kebutuhan tergantung ukuran keramik dan lebar nat.",
    metadata: { pack_size_kg: 1, color: "grey" }
  },
  {
    id: "10000000-0000-4000-8000-000000000017",
    name: "QHM Tile Spacer 2mm",
    category: "tiles",
    brand: "QHM",
    description: "Spacer 2 mm untuk menjaga jarak nat keramik tetap rata.",
    use_cases: ["spacer keramik", "pasang ubin", "nat rata"],
    unit: "pack 100 pcs",
    price: 18000,
    stock_status: "in_stock",
    coverage_note: "Kebutuhan tergantung jumlah tile.",
    metadata: { spacer_mm: 2, pieces: 100 }
  },
  {
    id: "10000000-0000-4000-8000-000000000018",
    name: "QHM Portland Cement 40kg",
    category: "wall_repair",
    brand: "QHM",
    description: "Semen portland untuk plester, acian dasar, dan perbaikan dinding.",
    use_cases: ["dinding retak", "plester", "semen", "perbaikan dinding"],
    unit: "bag 40 kg",
    price: 68000,
    stock_status: "in_stock",
    coverage_note: "Kebutuhan tergantung komposisi mortar dan ketebalan.",
    metadata: { pack_size_kg: 40 }
  },
  {
    id: "10000000-0000-4000-8000-000000000019",
    name: "QHM Skim Coat 20kg",
    category: "wall_repair",
    brand: "QHM",
    description: "Acian instan untuk meratakan permukaan dinding sebelum cat.",
    use_cases: ["acian", "dinding tidak rata", "persiapan cat", "skim coat"],
    unit: "bag 20 kg",
    price: 87000,
    stock_status: "in_stock",
    coverage_note: "Sekitar 10-15 m2 per bag untuk lapisan tipis.",
    metadata: { pack_size_kg: 20 }
  },
  {
    id: "10000000-0000-4000-8000-000000000020",
    name: "QHM Wall Putty 5kg",
    category: "wall_repair",
    brand: "QHM",
    description: "Dempul tembok untuk lubang kecil, retak rambut, dan bekas paku.",
    use_cases: ["dempul tembok", "retak rambut", "lubang paku", "persiapan cat"],
    unit: "pail 5 kg",
    price: 64000,
    stock_status: "in_stock",
    coverage_note: "Untuk tambalan lokal dan perataan tipis.",
    metadata: { pack_size_kg: 5 }
  },
  {
    id: "10000000-0000-4000-8000-000000000021",
    name: "QHM Sandpaper 240 Grit",
    category: "wall_repair",
    brand: "QHM",
    description: "Amplas halus untuk finishing dempul, cat lama, dan acian.",
    use_cases: ["amplas", "finishing dinding", "persiapan cat"],
    unit: "pack 10 sheets",
    price: 22000,
    stock_status: "in_stock",
    coverage_note: "Kebutuhan tergantung luas bidang dan kondisi permukaan.",
    metadata: { grit: 240, sheets: 10 }
  },
  {
    id: "10000000-0000-4000-8000-000000000022",
    name: "QHM Paint Brush 3 inch",
    category: "tools",
    brand: "QHM",
    description: "Kuas 3 inch untuk sudut dinding, pinggir plafon, dan detail waterproofing.",
    use_cases: ["kuas cat", "alat waterproofing", "sudut dinding"],
    unit: "pcs",
    price: 26000,
    stock_status: "in_stock",
    coverage_note: "Cocok untuk area detail dan pinggir.",
    metadata: { width_inch: 3 }
  },
  {
    id: "10000000-0000-4000-8000-000000000023",
    name: "QHM Mixing Bucket 20L",
    category: "tools",
    brand: "QHM",
    description: "Ember aduk untuk cat, waterproofing, perekat keramik, dan mortar ringan.",
    use_cases: ["ember", "aduk cat", "aduk semen", "alat renovasi"],
    unit: "pcs",
    price: 49000,
    stock_status: "in_stock",
    coverage_note: "Kapasitas 20 liter.",
    metadata: { capacity_l: 20 }
  },
  {
    id: "10000000-0000-4000-8000-000000000024",
    name: "QHM Scraper 4 inch",
    category: "tools",
    brand: "QHM",
    description: "Kape scraper untuk mengikis cat lama, meratakan dempul, dan membersihkan permukaan.",
    use_cases: ["scraper", "kape", "cat mengelupas", "dempul"],
    unit: "pcs",
    price: 34000,
    stock_status: "in_stock",
    coverage_note: "Ukuran 4 inch untuk pekerjaan dinding umum.",
    metadata: { width_inch: 4 }
  }
];

export function productEmbeddingText(product) {
  return [
    product.name,
    `Kategori: ${product.category}`,
    product.brand ? `Brand: ${product.brand}` : "",
    product.description,
    `Kegunaan: ${product.use_cases.join(", ")}`,
    product.coverage_note ? `Catatan coverage: ${product.coverage_note}` : ""
  ]
    .filter(Boolean)
    .join("\n");
}
